# remove archive
- when: thunderbird_archive_state == "absent" or thunderbird_archive_state == "reinstall"
  name: Remove {{ thunderbird_archive_dst }}
  become: true
  ansible.builtin.file:
    path: "{{ thunderbird_archive_dst }}"
    state: absent

# install archive
- when: thunderbird_archive_state == "present" or thunderbird_archive_state == "reinstall"
  block:

  # check dir
  - name: Check if {{ thunderbird_archive_dst }} already exists
    ansible.builtin.stat:
      path: "{{ thunderbird_archive_dst }}"
    register: __thunderbird_archive_dst
  
  # install archive
  # only if directory does not exist
  # important to prevent downgrades
  - when: __thunderbird_archive_dst.stat.exists == false
    name: Unarchive {{ thunderbird_archive }} to {{ thunderbird_archive_dst }} (only if dst does not exist)
    become: true
    ansible.builtin.unarchive:
      src: "{{ thunderbird_archive }}"
      dest: "{{ thunderbird_archive_dst | dirname }}"
      creates: thunderbird # "{{ thunderbird_archive_dst.split('/')[-1] }}" # /home/udo/thunderbird -> thunderbird
      mode: u=rwx,g=,o=rx
      owner: "{{ thunderbird_user if thunderbird_archive_exec.startswith('/home/') else 'root' }}"
      group: "{{ thunderbird_user if thunderbird_archive_exec.startswith('/home/') else 'root' }}"

  # link
  - name: Link {{ thunderbird_archive_link }} to {{ thunderbird_archive_exec }}
    become: true
    ansible.builtin.file:
      state: link
      src: "{{ thunderbird_archive_exec }}" # Path of file to link to
      dest: "{{ thunderbird_archive_link }}" # Path to file being managed (/path/to/symlink)
      owner: "{{ thunderbird_user if thunderbird_archive_exec.startswith('/home/') else 'root' }}"
      group: "{{ thunderbird_user if thunderbird_archive_exec.startswith('/home/') else 'root' }}"

  # desktop
  - name: Copy desktop file thunderbird.desktop
    become: true
    ansible.builtin.template:
      src: thunderbird.desktop.j2
      dest: "/usr/share/applications/thunderbird.desktop"
      owner: root
      group: root
      mode: u=rw,g=,o=r # world readable