---
# apt
- when: thunderbird_install_apt_state != None
  name: Apt thunderbird -> {{ thunderbird_install_apt_state }}
  become: true
  ansible.builtin.apt:
    name: thunderbird
    state: "{{ thunderbird_install_apt_state }}"