# remove
- when: thunderbird_install_opt_state == "absent" or thunderbird_install_opt_state == "reinstall"
  name: Remove {{ thunderbird_install_opt_dst }}
  become: true
  ansible.builtin.file:
    path: "{{ thunderbird_install_opt_dst }}"
    state: absent

# install
- when: thunderbird_install_opt_state == "present" or thunderbird_install_opt_state == "reinstall"
  block:

  # check dir
  - name: Check if {{ thunderbird_install_opt_dst }}" already exists
    ansible.builtin.stat:
      path: "{{ thunderbird_install_opt_dst }}"
    register: __thunderbird_dst
  
  # install
  - when: __thunderbird_dst.stat.exists == false
    block:
    
    # install from archive
    # only if directory does not exist
    # important to prevent downgrades
    - when: thunderbird_install_opt_from == "archive"
      name: Unarchive {{ thunderbird_install_opt_archive }} to {{ thunderbird_install_opt_dst }} (only if dst does not exist)
      become: true
      ansible.builtin.unarchive:
        src: "{{ thunderbird_install_opt_archive }}"
        dest: "{{ thunderbird_install_opt_dst | dirname }}"
        creates: thunderbird
        mode: u=rwx,g=,o=rx
        owner: "{{ thunderbird_user if thunderbird_install_opt_dst.startswith('/home/') else 'root' }}"
        group: "{{ thunderbird_user if thunderbird_install_opt_dst.startswith('/home/') else 'root' }}"

    # install from url
    - when: thunderbird_install_opt_from == "url"
      name: Install from url to {{ thunderbird_install_opt_dst }}
      become: true
      ansible.builtin.unarchive:
        src: "{{ thunderbird_install_opt_url }}"
        dest: "{{ thunderbird_install_opt_dst | dirname }}"
        remote_src: true
        owner: "{{ thunderbird_user if thunderbird_install_opt_dst.startswith('/home/') else 'root' }}"
        group: "{{ thunderbird_user if thunderbird_install_opt_dst.startswith('/home/') else 'root' }}"
        mode: u=rwx,g=rx,o=rx

  # link
  - name: Link {{ thunderbird_install_opt_link }} to {{ thunderbird_install_opt_exec }}
    become: true
    ansible.builtin.file:
      state: link
      src: "{{ thunderbird_install_opt_exec }}" # Path of file to link to
      dest: "{{ thunderbird_install_opt_link }}" # Path to file being managed (/path/to/symlink)
      owner: "{{ thunderbird_user if thunderbird_install_opt_dst.startswith('/home/') else 'root' }}"
      group: "{{ thunderbird_user if thunderbird_install_opt_dst.startswith('/home/') else 'root' }}"