---
- name: thunderbird role
  tags:
    - thunderbird
  block:

  # flatpak
  - ansible.builtin.import_tasks: thunderbird-install-flatpak.yml

  # apt
  - ansible.builtin.import_tasks: thunderbird-install-apt.yml

  # opt
  - ansible.builtin.import_tasks: thunderbird-install-opt.yml

  # desktop
  - ansible.builtin.import_tasks: thunderbird-desktop.yml

  # systemd user
  - ansible.builtin.import_tasks: thunderbird-systemd-user.yml
  
  # copy user data
  - ansible.builtin.import_tasks: thunderbird-copy-user-data.yml

  # cleanup
  - ansible.builtin.import_tasks: thunderbird-cleanup.yml