---
- name: thunderbird role
  tags:
    - thunderbird
  block:

  # flatpak
  - ansible.builtin.import_tasks: install_flatpak.yml

  # apt
  - ansible.builtin.import_tasks: install_apt.yml

  # opt
  - ansible.builtin.import_tasks: install_opt.yml

  # desktop
  - ansible.builtin.import_tasks: desktop.yml

  # systemd user
  - ansible.builtin.import_tasks: systemd_user.yml
  
  # copy user data
  - ansible.builtin.import_tasks: copy_user_data.yml

   