---
- name: thunderbird role
  tags:
    - thunderbird
  block:

  # flatpak
  - ansible.builtin.import_tasks: install_flatpak.yml

  # apt
  - ansible.builtin.import_tasks: install_apt.yml

  # opt
  - ansible.builtin.import_tasks: install_opt.yml

  # copy user data
  - when: 
    - thunderbird_user != None
    - thunderbird_user_data != None
    ansible.builtin.import_tasks: copy_user_data.yml

   