---
- name: systemctl --system daemon-reload
  become: true
  ansible.builtin.systemd_service:
    daemon_reload: true
    scope: system

- name: systemctl --user daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true
    scope: user
  become: true
  become_user: "{{ systemd_unit_user }}"
  when: 
    - __systemd_unit_user_daemon_check.stdout is defined
    - __systemd_unit_user_daemon_check.stdout in ['running', 'degraded', 'initializing']

- name: update-desktop-database
  become: true
  ansible.builtin.command: "update-desktop-database {{ thunderbird_desktop_dst | dirname }}"